"""add_bid_no_bid_fields

Revision ID: 1a5a3a264329
Revises: ca4654a07b43
Create Date: 2026-02-16 11:20:30.519658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a5a3a264329'
down_revision: Union[str, Sequence[str], None] = 'ca4654a07b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice_match', sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notice_match', sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notice_match', sa.Column('recommendation_reasons', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice_match', 'recommendation_reasons')
    op.drop_column('notice_match', 'checklist')
    op.drop_column('notice_match', 'risk_flags')
    # ### end Alembic commands ###
