"""initial schema

Revision ID: ca4654a07b43
Revises: 
Create Date: 2026-02-13 16:35:35.374917

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'ca4654a07b43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pgvector extension is enabled
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('canonical_name', sa.Text(), nullable=False),
        sa.Column('slug', sa.Text(), nullable=True),
        sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    op.create_table('ingestion_log',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('items_processed', sa.Integer(), nullable=True),
        sa.Column('error_details', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_profile',
        sa.Column('org_id', sa.UUID(), nullable=False),
        sa.Column('charity_number', sa.String(length=20), nullable=True),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('latest_income', sa.BigInteger(), nullable=True),
        sa.Column('mission', sa.Text(), nullable=True),
        sa.Column('vision', sa.Text(), nullable=True),
        sa.Column('programs_services', sa.Text(), nullable=True),
        sa.Column('target_population', sa.Text(), nullable=True),
        sa.Column('ukcat_codes', sa.ARRAY(sa.Text()), nullable=True),
        sa.Column('beneficiary_groups', sa.ARRAY(sa.Text()), nullable=True),
        sa.Column('inferred_cpv_codes', sa.ARRAY(sa.Text()), nullable=True),
        sa.Column('service_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('min_contract_value', sa.Integer(), nullable=True),
        sa.Column('max_contract_value', sa.Integer(), nullable=True),
        sa.Column('profile_embedding', Vector(1536), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('org_id'),
        sa.UniqueConstraint('charity_number')
    )
    op.create_table('notice',
        sa.Column('ocid', sa.Text(), nullable=False),
        sa.Column('release_id', sa.Text(), nullable=True),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('provider_summary', sa.Text(), nullable=True),
        sa.Column('provider_summary_embedding', Vector(1536), nullable=True),
        sa.Column('buyer_id', sa.UUID(), nullable=True),
        sa.Column('publication_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deadline_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column('value_currency', sa.String(length=3), nullable=True),
        sa.Column('procurement_method', sa.String(length=50), nullable=True),
        sa.Column('notice_type', sa.String(length=50), nullable=True),
        sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('source_url', sa.Text(), nullable=True),
        sa.Column('cpv_codes', sa.ARRAY(sa.Text()), nullable=True),
        sa.Column('embedding', Vector(1536), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('is_archived', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
        sa.PrimaryKeyConstraint('ocid')
    )
    op.create_table('notice_match',
        sa.Column('org_id', sa.UUID(), nullable=False),
        sa.Column('notice_id', sa.Text(), nullable=False),
        sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('score_semantic', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('score_domain', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('score_geo', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('feedback_status', sa.String(length=20), nullable=True),
        sa.Column('viability_warning', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['notice_id'], ['notice.ocid'], ),
        sa.ForeignKeyConstraint(['org_id'], ['service_profile.org_id'], ),
        sa.PrimaryKeyConstraint('org_id', 'notice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice_match')
    op.drop_table('notice')
    op.drop_table('service_profile')
    op.drop_table('ingestion_log')
    op.drop_table('buyer')
    # ### end Alembic commands ###
